# 实例的副本数
replicaCount: 1

# 应用的镜像及拉取规则
image:
  repository: registry.saas.crland.com.cn/crland-monitor-portal/ued-pc-web
  pullPolicy: IfNotPresent

# 资源请求和限制
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 128Mi

# 健康检查，通过则接入流量
readinessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

# 健康检查，不通过时重启容器
livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 3
